# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
- job: BuildAndTest
  pool:
    vmImage: 'Ubuntu 16.04'

  condition: ne(variables['Build.SourceBranch'], 'refs/heads/gh-pages')

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.9'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
    displayName: 'npm install'

  - script: |
      ng lint
    displayName: 'tslint'

  - script: |
      ng build --prod
    displayName: 'build distribution'

  - script: |
      ng test --watch=false --browsers ChromeHeadless --code-coverage
    displayName: 'execute tests'

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: JUnit
      testResultsFiles: ./test-results/junit.xml

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'

- job: Deploy
  dependsOn: BuildAndTest
  pool:
    vmImage: 'Ubuntu 16.04'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.9'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install -g workbox-cli@3.6.3
      npm install
      npm i angular-cli-ghpages@0.5.3 --save-dev
    displayName: 'npm install'

  - script: |
      git remote set-url origin https://$GH_TOKEN@github.com/eQualityTime/ovfplayer.git
      git config user.name "eQualityTimeDevs"
      git config user.email "support@equalitytime.co.uk"
      git tag -a $BUILD_BUILDNUMBER -m "Release tagging"
      git push --tags
    displayName: 'Tag and release'

  - script: |
      node git_version.js
    displayName: 'Git describe'

  - script: |
      ng build --prod --base-href "https://equalitytime.github.io/ovfplayer/"
      workbox injectManifest
    displayName: 'build with correct HREF'

  - script: |
      npx ngh --dir=dist/open-voice-factory --repo=https://$GH_TOKEN@github.com/eQualityTime/ovfplayer.git --name="eQualityTimeDevs" --email="support@equalitytime.co.uk"
    displayName: 'deploy to gh-pages'

- job: DeployStaging
  dependsOn: BuildAndTest
  pool:
    vmImage: 'Ubuntu 16.04'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.9'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install -g workbox-cli@3.6.3
      npm install
      npm i angular-cli-ghpages@0.5.3 --save-dev
    displayName: 'npm install'

  - script: |
      ng build --base-href "https://equalitytime.github.io/teststaging/" --configuration=staging
      workbox injectManifest
    displayName: 'build with correct HREF'

  - script: |
      npx ngh --dir=dist/open-voice-factory --repo=https://$GH_TOKEN@github.com/eQualityTime/teststaging.git --name="eQualityTimeDevs" --email="support@equalitytime.co.uk"
    displayName: 'deploy to gh-pages'
