# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
- job: BuildAndTest
  pool:
    vmImage: 'Ubuntu 16.04'

  condition: ne(variables['Build.SourceBranch'], 'refs/heads/gh-pages')

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
    displayName: 'npm install'

  - script: |
      ng build --prod
    displayName: 'build distribution'

  - script: |
      ng test --watch=false --browsers ChromeHeadless
    displayName: 'execute tests'

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: JUnit
      testResultsFiles: ./test-results/junit.xml

- job: Deploy
  dependsOn: BuildAndTest
  pool:
    vmImage: 'Ubuntu 16.04'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
      npm i angular-cli-ghpages --save-dev
    displayName: 'npm install'

  - script: |
      node git_version.js
    displayName: 'Git describe'

  - script: |
      ng build --prod --base-href "https://equalitytime.github.io/ovfplayer/"
    displayName: 'build with correct HREF'

  - script: |
      npx ngh --dir=dist/open-voice-factory --repo=https://$GH_TOKEN@github.com/eQualityTime/ovfplayer.git --name="psi77" --email="simon@smith77.co.uk"
    displayName: 'deploy to gh-pages'
