# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'gh-pages'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 10.13.x
      uses: actions/setup-node@v4
      with:
        node-version: 10.13.x
        cache: 'npm'
    - name: npm install
      run: npm ci
    - name: tslint
      run: npm run lint
    - name: build distribution
      run: npm run build --prod

    - name: Execute tests
      id: test
      run: npm run ng test -- --watch=false --browsers=ChromeHeadless --code-coverage

    - name: Upload test results artifact
      if: steps.test.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: test-results/junit.xml

    - name: Upload code coverage artifact
      if: steps.test.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: CodeCoverageResults
        path: coverage/

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2.4.1
      if: steps.test.outcome == 'success'
      with:
        files: "test-results/junit.xml"
        
    - name: Publish code coverage results
      uses: ./.github/actions/code-coverage-action
      if: steps.test.outcome == 'success'
      with: 
        coverage-filename: 'coverage/cobertura-coverage.xml'
        check-minimum: 80
        summary-thresholds: '75 85'
    
